version: '3.5'

networks:
  cluster-network:

services:
   
  seed:
    networks:
      - cluster-network
    image: akka-stock-trading-system/trade-order-service
    ports:
      - '2553:2553'
      - '7000:7000'
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: seed
      CLUSTER_SEED_IP: seed
      CASSANDRA_IP: 192.168.2.45
      CASSANDRA_PORT: 9042
      KAFKA_SERVER: 192.168.2.45:9092
      SERVER_PORT: 7000


  node1:
    networks:
      - cluster-network
    image: akka-stock-trading-system/trade-order-service
    ports:
      - '7001:7000'    
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: node1
      CLUSTER_PORT: 1600
      CLUSTER_SEED_IP: seed
      CLUSTER_SEED_PORT: 2553
      CASSANDRA_IP: 192.168.2.45
      CASSANDRA_PORT: 9042
      KAFKA_SERVER: 192.168.2.45:9092
      SERVER_PORT: 7000

  node2:
    networks:
      - cluster-network
    image: akka-stock-trading-system/trade-order-service
    ports:
      - '7002:7000'
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: node2
      CLUSTER_PORT: 1600
      CLUSTER_SEED_IP: seed
      CLUSTER_SEED_PORT: 2553
      CASSANDRA_IP: 192.168.2.45
      CASSANDRA_PORT: 9042
      KAFKA_SERVER: 192.168.2.45:9092
      SERVER_PORT: 7000

 