version: '3.5'

networks:
  cluster-network-portfolio:

services:
   
  seed-portfolio:
    networks:
      - cluster-network-portfolio
    image: akka-stock-trading-system/portfolio-service
    ports:
      - '2554:2554'
      - '7000:7000'
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: seed-portfolio
      CLUSTER_SEED_IP: seed-portfolio
      CLUSTER_PORT: 2554
      CLUSTER_SEED_PORT: 2554
      CASSANDRA_IP: 192.168.2.45
      CASSANDRA_PORT: 9042
      KAFKA_SERVER: 192.168.2.45:9092
      SERVER_PORT: 7000


  node1:
    networks:
      - cluster-network-portfolio
    image: akka-stock-trading-system/portfolio-service
    ports:
      - '7001:7000' 
      - '1500:1500'
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: node1
      CLUSTER_PORT: 1500
      CLUSTER_SEED_IP: seed-portfolio
      CLUSTER_SEED_PORT: 2554
      CASSANDRA_IP: 192.168.2.45
      CASSANDRA_PORT: 9042
      KAFKA_SERVER: 192.168.2.45:9092
      SERVER_PORT: 7000

  node2:
    networks:
      - cluster-network-portfolio
    image: akka-stock-trading-system/portfolio-service
    ports:
      - '7002:7000'
      - '1501:1501'
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: node2
      CLUSTER_PORT: 1501
      CLUSTER_SEED_IP: seed-portfolio
      CLUSTER_SEED_PORT: 2554
      CASSANDRA_IP: 192.168.2.45
      CASSANDRA_PORT: 9042
      KAFKA_SERVER: 192.168.2.45:9092
      SERVER_PORT: 7000

  node3:
    networks:
      - cluster-network-portfolio
    image: akka-stock-trading-system/portfolio-service
    ports:
      - '7003:7000'
      - '1502:1502'
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: node3
      CLUSTER_PORT: 1502
      CLUSTER_SEED_IP: seed-portfolio
      CLUSTER_SEED_PORT: 2554
      CASSANDRA_IP: 192.168.2.45
      CASSANDRA_PORT: 9042
      KAFKA_SERVER: 192.168.2.45:9092
      SERVER_PORT: 7000


 